apiVersion: apps/v1
kind: Deployment
metadata:
  name: container1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container1
  template:
    metadata:
      labels:
        app: container1
    spec:
      containers:
        - name: container1
          image: gcr.io/YOUR_PROJECT_ID/container1:latest
          ports:
            - containerPort: 6000
          volumeMounts:
            - mountPath: /disha_PV_dir
              name: persistent-storage
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: disha-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: container1-service
spec:
  type: LoadBalancer
  selector:
    app: container1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6000
